### ISSUE TITLE
Choose solver type using config files

### ISSUE THREAD

**Issue by cdgreenidge** [nanoverse-simulations/nanoverse#16]
Right now I'm hard coding the band LU solver into ContinuumSolverFactory in my dev branch. Should we decide to include more than one solver method, it would be nice if the user could select the solver type (maybe with sensible defaults) in the config file. 

I want to hold off for now though because I don't foresee the need for solver selection once multigrid or spectral solvers are implemented. However it should be addressed before merging to master (this is a note to self so I don't forget).

**Comment by borenstein** [comment]
So you know, the entire factory package is going away in the next couple of weeks, to be replaced by symbol tables for a domain-specific language (see the compiler branch for more info). So don't put too much effort into this right now.
